---
# MKDocs configuration
# https://www.mkdocs.org/
# =============================================================================
# Configuraiton file describing the documentation using mkdocs.

# Website Information
# ---------------------------------------------------------------------------
site_name: MyRepo
site_description: >-
  TODO
site_url: https://docs.romaindeville.fr/dotfiles/config/mr

# Repository Information
# ---------------------------------------------------------------------------
repo_name: Framagit
repo_url: https://framagit.org/rdeville.public/my_dotfiles/myrepo
edit_uri: rdeville.public/my_dotfiles/myrepo/edit/develop/.docs/config/mr/docs
extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://framagit.org/rdeville.public/my_dotfiles/myrepo

# This setting controls the style used for linking to pages within the
# documentation.
use_directory_urls: false

# Theme Configuration
# ---------------------------------------------------------------------------
theme:
  # Using mkdocs-material theme
  # https://squidfunk.github.io/mkdocs-material/
  name: material
  # Overriding parent theme configuration
  custom_dir: docs/theme
  # Determines whether the search plugin expects the theme to provide a
  # dedicated search page via a template located at search/search.html.
  include_search_page: false
  # Determines whether the search plugin should only generate a search
  # index or a complete search solution.
  search_index_only: true
  # Language site
  language: en
  # Optional features like tabs and instant loading are now implemented
  # as flags and can be enabled by listing them in mkdocs.yml under
  # theme.features:
  feature:
    tabs: false
  # Setting colors palette (these are defined in docs/theme/css/colors.css
  palette:
    primary: drac-yellow
    accent: drac-yellow
  # Font configuration for the website (FurCode are provided in
  # docs/theme/fonts)
  font:
    text: FuraCode Nerd Font
    code: FuraCode Nerd Font
  # Path to logo and icons to use for the website
  logo: "assets/img/myrepo_logo.svg"
  icon:
    repo: fontawesome/brands/gitlab
  favicon: "assets/img/myrepo_logo.svg"

# External CSS
# ---------------------------------------------------------------------------
extra_css:
  # Define cutom fonts
  - theme/css/fonts.css
  # Define cutom css when using attr_list
  # https://python-markdown.github.io/extensions/attr_list/
  - theme/css/attr_list.css
  # Define custom color palette
  # From: https://github.com/facelessuser/pymdown-extensions
  - theme/css/colors.css
  # Define custom mkdocstring css
  # From: https://github.com/pawamoy/mkdocstrings/blob/master/docs/css/mkdocstrings.css
  - theme/css/mkdocstring.css

# External JS
# ---------------------------------------------------------------------------
extra_javascript:
  # Mermaid js
  - https://unpkg.com/mermaid@8.6.3/dist/mermaid.min.js

# Plugins
# ---------------------------------------------------------------------------
plugins:
  - search:
    # https://spotify.github.io/mkdocs-monorepo-plugin/
    # This plugin enables you to build multiple sets of documentation in a
    # single Mkdocs.
    #- monorepo:
    # https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
    # MkDocs plugin that enables displaying the date of the last git
    # modification of a page.
  - git-revision-date-localized:
      locale: en
      fallback_to_build_date: true
    # https://github.com/fralau/mkdocs-mermaid2-plugin#declaring-the-superfences-extension
    # An MkDocs plugin that renders textual graph descriptions into Mermaid
    # graphs (flow charts, sequence diagrams, pie charts, etc.).
  - mermaid2:
      arguments:
        theme: 'dark'
    # https://pawamoy.github.io/mkdocstrings/
    # Automatic documentation from sources, for MkDocs.
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
          setup_commands:
            - import sys
            - sys.path.append(".direnv/src")
      watch:
        - .direnv/src/

# Extensions
# ---------------------------------------------------------------------------
markdown_extensions:
  - markdown_include.include:
      base_path: docs
  # Python Markdown Extensions
  # https://python-markdown.github.io/extensions/
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: ""
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.meta:
  - markdown.extensions.md_in_html:
  # Pymdown Extensions
  # https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/
  - pymdownx.betterem:
  - pymdownx.superfences:
      preserve_tabs: true
      # Make exceptions to highlighting code of following classes:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:
  # Locally installed in docs/theme/plugins/ from original repo
  # https://github.com/g-provost/lightgallery-markdown
  - lightgallery:

# Website architecture
# ---------------------------------------------------------------------------
nav:
  - Home: index.md
  - Requirements: requirements.md
  - Guides:
    - Developers guide: guides/developers_guide.md
    - Administrator guide: guides/administrator_guide.md
    - User guide: guides/user_guide.md
    - Syntax guide: guides/syntax_guide.md
  - Tutorials:
    - Introduction: tutorials/introduction.md
    - Git Branch Management: tutorials/git_branch_management.md
    - Update Documentation: tutorials/update_documentation.md
    - Update Roles: tutorials/update_roles.md
  - Contributing to PAGoDA: contributing.md
  - Appendix:
    - Introduction: appendix.md
    - Lexicon: appendix.html#lexicon
    - External Documentation: appendix.html#external-documentation
  - About:
    - Release Notes: about/release_notes.md
    - FAQ: about/FAQ.md
    - License: about/license.md
    - Code of conduct: about/code_of_conduct.md
    - Data Privacy: about/data_privacy.md

# *****************************************************************************
# EDITOR CONFIG
# vim: ft=yaml: ts=2: sw=2: sts=2
# *****************************************************************************
